<?php

namespace App\Database\Seeds;

use CodeIgniter\Database\Seeder;

class MenuSeeder extends Seeder
{
    public function run()
    {
        $data = [
            [
                'menuId'		=> 100001,
				'menuPid'		=> 0,
				'menuTypeId'	=> 100001,
				'menu'			=> "DASHBOARD",
				'icon'			=> "-",
				'url'			=> "-",
				'urlType'		=> "1",
				'menuLevel'		=> "1",
				'title'			=> "DASHBOARD",
				'menuOrder'		=> 0,
				'statusId'		=> 1,
				'view'			=> 1,
				'created'		=> 0,
				'updated'		=> 0,
				'cancelled'		=> 0,
				'deleted'		=> 0,
				'printed'		=> 0,
				'downloaded'	=> 0,
				'closed'		=> 0,
				'verified'		=> 0,
				'inputBy'		=>  "100001",
                'inputDate'		=>  date('Y-m-d H:i:s'),
            ],
			[
                'menuId'		=> 100002,
				'menuPid'		=> 100001,
				'menuTypeId'	=> 100001,
				'menu'			=> "SETTING",
				'icon'			=> "-",
				'url'			=> "-",
				'urlType'		=> "1",
				'menuLevel'		=> "2",
				'title'			=> "SETTING",
				'menuOrder'		=> 6,
				'statusId'		=> 1,
				'view'			=> 1,
				'created'		=> 0,
				'updated'		=> 0,
				'cancelled'		=> 0,
				'deleted'		=> 0,
				'printed'		=> 0,
				'downloaded'	=> 0,
				'closed'		=> 0,
				'verified'		=> 0,
				'inputBy'		=>  "100001",
                'inputDate'		=>  date('Y-m-d H:i:s'),
            ],
			[
                'menuId'		=> 100003,
				'menuPid'		=> 100002,
				'menuTypeId'	=> 100001,
				'menu'			=> "SETTING USERS",
				'icon'			=> "users.png",
				'url'			=> "users/manage",
				'urlType'		=> "1",
				'menuLevel'		=> "3",
				'title'			=> "SETTING USERS",
				'menuOrder'		=> 7,
				'statusId'		=> 1,
				'view'			=> 1,
				'created'		=> 1,
				'updated'		=> 1,
				'cancelled'		=> 0,
				'deleted'		=> 1,
				'printed'		=> 0,
				'downloaded'	=> 0,
				'closed'		=> 0,
				'verified'		=> 0,
				'inputBy'		=>  "100001",
                'inputDate'		=>  date('Y-m-d H:i:s'),
            ],
			[
                'menuId'		=> 100004,
				'menuPid'		=> 100002,
				'menuTypeId'	=> 100001,
				'menu'			=> "SETTING GROUPS",
				'icon'			=> "group.png",
				'url'			=> "groups/manage",
				'urlType'		=> "1",
				'menuLevel'		=> "3",
				'title'			=> "SETTING GROUPS",
				'menuOrder'		=> 8,
				'statusId'		=> 1,
				'view'			=> 1,
				'created'		=> 1,
				'updated'		=> 1,
				'cancelled'		=> 0,
				'deleted'		=> 1,
				'printed'		=> 0,
				'downloaded'	=> 0,
				'closed'		=> 0,
				'verified'		=> 0,
				'inputBy'		=>  "100001",
                'inputDate'		=>  date('Y-m-d H:i:s'),
            ],
			[
                'menuId'		=> 100005,
				'menuPid'		=> 100002,
				'menuTypeId'	=> 100001,
				'menu'			=> "SETTING PERMISSIONS",
				'icon'			=> "permission.png",
				'url'			=> "perm/manage",
				'urlType'		=> "1",
				'menuLevel'		=> "3",
				'title'			=> "SETTING PERMISSIONS",
				'menuOrder'		=> 9,
				'statusId'		=> 1,
				'view'			=> 1,
				'created'		=> 1,
				'updated'		=> 1,
				'cancelled'		=> 0,
				'deleted'		=> 1,
				'printed'		=> 0,
				'downloaded'	=> 0,
				'closed'		=> 0,
				'verified'		=> 0,
				'inputBy'		=>  "100001",
                'inputDate'		=>  date('Y-m-d H:i:s'),
            ],
			[
                'menuId'		=> 100006,
				'menuPid'		=> 100002,
				'menuTypeId'	=> 100001,
				'menu'			=> "SETTING MENU",
				'icon'			=> "menu.png",
				'url'			=> "menu/manage",
				'urlType'		=> "1",
				'menuLevel'		=> "3",
				'title'			=> "SETTING MENU",
				'menuOrder'		=> 10,
				'statusId'		=> 1,
				'view'			=> 1,
				'created'		=> 1,
				'updated'		=> 1,
				'cancelled'		=> 0,
				'deleted'		=> 1,
				'printed'		=> 0,
				'downloaded'	=> 0,
				'closed'		=> 0,
				'verified'		=> 0,
				'inputBy'		=>  "100001",
                'inputDate'		=>  date('Y-m-d H:i:s'),
            ],
			[
                'menuId'		=> 100007,
				'menuPid'		=> 100001,
				'menuTypeId'	=> 100001,
				'menu'			=> "TOOL",
				'icon'			=> "general.png",
				'url'			=> "-",
				'urlType'		=> "1",
				'menuLevel'		=> "2",
				'title'			=> "TOOL",
				'menuOrder'		=> 11,
				'statusId'		=> 1,
				'view'			=> 1,
				'created'		=> 0,
				'updated'		=> 0,
				'cancelled'		=> 0,
				'deleted'		=> 0,
				'printed'		=> 0,
				'downloaded'	=> 0,
				'closed'		=> 0,
				'verified'		=> 0,
				'inputBy'		=>  "100001",
                'inputDate'		=>  date('Y-m-d H:i:s'),
            ],
			[
                'menuId'		=> 100008,
				'menuPid'		=> 100007,
				'menuTypeId'	=> 100001,
				'menu'			=> "HISTORY LOGIN",
				'icon'			=> "history.png",
				'url'			=> "logLogin/manage",
				'urlType'		=> "1",
				'menuLevel'		=> "3",
				'title'			=> "HISTORY LOGIN",
				'menuOrder'		=> 12,
				'statusId'		=> 1,
				'view'			=> 1,
				'created'		=> 1,
				'updated'		=> 1,
				'cancelled'		=> 0,
				'deleted'		=> 1,
				'printed'		=> 0,
				'downloaded'	=> 0,
				'closed'		=> 0,
				'verified'		=> 0,
				'inputBy'		=>  "100001",
                'inputDate'		=>  date('Y-m-d H:i:s'),
            ],
			[
                'menuId'		=> 100009,
				'menuPid'		=> 100001,
				'menuTypeId'	=> 100001,
				'menu'			=> "SALES ORDER",
				'icon'			=> "customer.png",
				'url'			=> "-",
				'urlType'		=> "1",
				'menuLevel'		=> "2",
				'title'			=> "SALES ORDER",
				'menuOrder'		=> 4,
				'statusId'		=> 1,
				'view'			=> 1,
				'created'		=> 0,
				'updated'		=> 0,
				'cancelled'		=> 0,
				'deleted'		=> 0,
				'printed'		=> 0,
				'downloaded'	=> 0,
				'closed'		=> 0,
				'verified'		=> 0,
				'inputBy'		=>  "100001",
                'inputDate'		=>  date('Y-m-d H:i:s'),
            ],
			[
                'menuId'		=> 100010,
				'menuPid'		=> 100009,
				'menuTypeId'	=> 100001,
				'menu'			=> "CUSTOMER",
				'icon'			=> "customer.png",
				'url'			=> "customers/manage",
				'urlType'		=> "1",
				'menuLevel'		=> "5",
				'title'			=> "CUSTOMER",
				'menuOrder'		=> 7,
				'statusId'		=> 1,
				'view'			=> 1,
				'created'		=> 1,
				'updated'		=> 1,
				'cancelled'		=> 0,
				'deleted'		=> 1,
				'printed'		=> 0,
				'downloaded'	=> 0,
				'closed'		=> 0,
				'verified'		=> 0,
				'inputBy'		=>  "100001",
                'inputDate'		=>  date('Y-m-d H:i:s'),
            ],
			[
                'menuId'		=> 100011,
				'menuPid'		=> 100001,
				'menuTypeId'	=> 100001,
				'menu'			=> "MASTER DATA",
				'icon'			=> "-",
				'url'			=> "-",
				'urlType'		=> "1",
				'menuLevel'		=> "2",
				'title'			=> "MASTER DATA",
				'menuOrder'		=> 7,
				'statusId'		=> 1,
				'view'			=> 1,
				'created'		=> 1,
				'updated'		=> 1,
				'cancelled'		=> 0,
				'deleted'		=> 1,
				'printed'		=> 0,
				'downloaded'	=> 0,
				'closed'		=> 0,
				'verified'		=> 0,
				'inputBy'		=>  "100001",
                'inputDate'		=>  date('Y-m-d H:i:s'),
            ],
			[
                'menuId'		=> 100012,
				'menuPid'		=> 100011,
				'menuTypeId'	=> 100001,
				'menu'			=> "PRODUCT ITEMS",
				'icon'			=> "guide.png",
				'url'			=> "products/manage",
				'urlType'		=> "1",
				'menuLevel'		=> "3",
				'title'			=> "PRODUCT ITEMS",
				'menuOrder'		=> 3,
				'statusId'		=> 1,
				'view'			=> 1,
				'created'		=> 1,
				'updated'		=> 1,
				'cancelled'		=> 0,
				'deleted'		=> 1,
				'printed'		=> 0,
				'downloaded'	=> 0,
				'closed'		=> 0,
				'verified'		=> 0,
				'inputBy'		=>  "100001",
                'inputDate'		=>  date('Y-m-d H:i:s'),
            ],
			[
                'menuId'		=> 100013,
				'menuPid'		=> 100011,
				'menuTypeId'	=> 100001,
				'menu'			=> "LOCATION",
				'icon'			=> "customer.png",
				'url'			=> "location/manage",
				'urlType'		=> "1",
				'menuLevel'		=> "3",
				'title'			=> "LOCATION",
				'menuOrder'		=> 2,
				'statusId'		=> 1,
				'view'			=> 1,
				'created'		=> 1,
				'updated'		=> 1,
				'cancelled'		=> 0,
				'deleted'		=> 1,
				'printed'		=> 0,
				'downloaded'	=> 0,
				'closed'		=> 0,
				'verified'		=> 0,
				'inputBy'		=>  "100001",
                'inputDate'		=>  date('Y-m-d H:i:s'),
            ],
        ];
        $this->db->table('menu')->insertBatch($data);
    }
}
