<?php

namespace App\Database\Seeds;

use CodeIgniter\Database\Seeder;

class MenuSeeder extends Seeder
{
	public function run()
	{
		$now = date('Y-m-d H:i:s');

		$data = [
			['menuId' => 100001, 'menuPid' => 0, 'menuTypeId' => 100001, 'menu' => 'DASHBOARD', 'icon' => '-', 'url' => '-', 'urlType' => '1', 'menuLevel' => 1, 'title' => 'DASHBOARD', 'menuOrder' => 0, 'statusId' => 1, 'view' => 1, 'created' => 1, 'updated' => 0, 'cancelled' => 0, 'deleted' => 0, 'printed' => 0, 'downloaded' => 0, 'closed' => 0, 'verified' => 0, 'inputBy' => '100001', 'inputDate' => $now],
			['menuId' => 100002, 'menuPid' => 100001, 'menuTypeId' => 100001, 'menu' => 'SETTING', 'icon' => '-', 'url' => '-', 'urlType' => '1', 'menuLevel' => 2, 'title' => 'SETTING', 'menuOrder' => 16, 'statusId' => 1, 'view' => 1, 'created' => 1, 'updated' => 0, 'cancelled' => 0, 'deleted' => 0, 'printed' => 0, 'downloaded' => 0, 'closed' => 0, 'verified' => 0, 'inputBy' => '100001', 'inputDate' => $now],
			['menuId' => 100003, 'menuPid' => 100002, 'menuTypeId' => 100001, 'menu' => 'SETTING USERS', 'icon' => 'users.png', 'url' => 'users/manage', 'urlType' => '1', 'menuLevel' => 3, 'title' => 'SETTING USERS', 'menuOrder' => 17, 'statusId' => 1, 'view' => 1, 'created' => 1, 'updated' => 1, 'cancelled' => 0, 'deleted' => 1, 'printed' => 0, 'downloaded' => 0, 'closed' => 0, 'verified' => 0, 'inputBy' => '100001', 'inputDate' => $now],
			['menuId' => 100004, 'menuPid' => 100002, 'menuTypeId' => 100001, 'menu' => 'SETTING GROUPS', 'icon' => 'group.png', 'url' => 'groups/manage', 'urlType' => '1', 'menuLevel' => 3, 'title' => 'SETTING GROUPS', 'menuOrder' => 18, 'statusId' => 1, 'view' => 1, 'created' => 1, 'updated' => 1, 'cancelled' => 0, 'deleted' => 1, 'printed' => 0, 'downloaded' => 0, 'closed' => 0, 'verified' => 0, 'inputBy' => '100001', 'inputDate' => $now],
			['menuId' => 100005, 'menuPid' => 100002, 'menuTypeId' => 100001, 'menu' => 'SETTING PERMISSIONS', 'icon' => 'permission.png', 'url' => 'perm/manage', 'urlType' => '1', 'menuLevel' => 3, 'title' => 'SETTING PERMISSIONS', 'menuOrder' => 19, 'statusId' => 1, 'view' => 1, 'created' => 1, 'updated' => 1, 'cancelled' => 0, 'deleted' => 1, 'printed' => 0, 'downloaded' => 0, 'closed' => 0, 'verified' => 0, 'inputBy' => '100001', 'inputDate' => $now],
			['menuId' => 100006, 'menuPid' => 100002, 'menuTypeId' => 100001, 'menu' => 'SETTING MENU', 'icon' => 'menu.png', 'url' => 'menu/manage', 'urlType' => '1', 'menuLevel' => 3, 'title' => 'SETTING MENU', 'menuOrder' => 20, 'statusId' => 1, 'view' => 1, 'created' => 1, 'updated' => 1, 'cancelled' => 0, 'deleted' => 1, 'printed' => 0, 'downloaded' => 0, 'closed' => 0, 'verified' => 0, 'inputBy' => '100001', 'inputDate' => $now],
			['menuId' => 100007, 'menuPid' => 100001, 'menuTypeId' => 100001, 'menu' => 'TOOL', 'icon' => 'general.png', 'url' => '-', 'urlType' => '1', 'menuLevel' => 2, 'title' => 'TOOL', 'menuOrder' => 21, 'statusId' => 1, 'view' => 1, 'created' => 1, 'updated' => 0, 'cancelled' => 0, 'deleted' => 0, 'printed' => 0, 'downloaded' => 0, 'closed' => 0, 'verified' => 0, 'inputBy' => '100001', 'inputDate' => $now],
			['menuId' => 100008, 'menuPid' => 100007, 'menuTypeId' => 100001, 'menu' => 'HISTORY LOGIN', 'icon' => 'history.png', 'url' => 'logLogin/manage', 'urlType' => '1', 'menuLevel' => 3, 'title' => 'HISTORY LOGIN', 'menuOrder' => 22, 'statusId' => 1, 'view' => 1, 'created' => 1, 'updated' => 1, 'cancelled' => 0, 'deleted' => 1, 'printed' => 0, 'downloaded' => 0, 'closed' => 0, 'verified' => 0, 'inputBy' => '100001', 'inputDate' => $now],
			['menuId' => 100009, 'menuPid' => 100001, 'menuTypeId' => 100001, 'menu' => 'SALES ORDER', 'icon' => 'customer.png', 'url' => '-', 'urlType' => '1', 'menuLevel' => 2, 'title' => 'SALES ORDER', 'menuOrder' => 8, 'statusId' => 1, 'view' => 1, 'created' => 1, 'updated' => 0, 'cancelled' => 0, 'deleted' => 0, 'printed' => 0, 'downloaded' => 0, 'closed' => 0, 'verified' => 0, 'inputBy' => '100001', 'inputDate' => $now],
			['menuId' => 100010, 'menuPid' => 100011, 'menuTypeId' => 100001, 'menu' => 'CUSTOMER', 'icon' => 'customer.png', 'url' => 'customers/manage', 'urlType' => '1', 'menuLevel' => 3, 'title' => 'CUSTOMER', 'menuOrder' => 2, 'statusId' => 1, 'view' => 1, 'created' => 1, 'updated' => 1, 'cancelled' => 0, 'deleted' => 1, 'printed' => 0, 'downloaded' => 0, 'closed' => 0, 'verified' => 0, 'inputBy' => '100001', 'inputDate' => $now],
			['menuId' => 100011, 'menuPid' => 100001, 'menuTypeId' => 100001, 'menu' => 'MASTER DATA', 'icon' => '-', 'url' => '-', 'urlType' => '1', 'menuLevel' => 2, 'title' => 'MASTER DATA', 'menuOrder' => 1, 'statusId' => 1, 'view' => 1, 'created' => 1, 'updated' => 1, 'cancelled' => 0, 'deleted' => 1, 'printed' => 0, 'downloaded' => 0, 'closed' => 0, 'verified' => 0, 'inputBy' => '100001', 'inputDate' => $now],
			['menuId' => 100012, 'menuPid' => 100011, 'menuTypeId' => 100001, 'menu' => 'PRODUCT ITEMS', 'icon' => 'guide.png', 'url' => 'products/manage', 'urlType' => '1', 'menuLevel' => 3, 'title' => 'PRODUCT ITEMS', 'menuOrder' => 3, 'statusId' => 1, 'view' => 1, 'created' => 1, 'updated' => 1, 'cancelled' => 0, 'deleted' => 1, 'printed' => 0, 'downloaded' => 0, 'closed' => 0, 'verified' => 0, 'inputBy' => '100001', 'inputDate' => $now],
			['menuId' => 100013, 'menuPid' => 100011, 'menuTypeId' => 100001, 'menu' => 'LOCATION', 'icon' => 'customer.png', 'url' => 'locations/manage', 'urlType' => '1', 'menuLevel' => 3, 'title' => 'LOCATION', 'menuOrder' => 4, 'statusId' => 1, 'view' => 1, 'created' => 1, 'updated' => 1, 'cancelled' => 0, 'deleted' => 1, 'printed' => 0, 'downloaded' => 0, 'closed' => 0, 'verified' => 0, 'inputBy' => '100001', 'inputDate' => $now],
			['menuId' => 100014, 'menuPid' => 100009, 'menuTypeId' => 100001, 'menu' => 'SALES ORDER', 'icon' => 'customer.png', 'url' => 'salesorders/manage', 'urlType' => '', 'menuLevel' => 3, 'title' => 'SALES ORDER', 'menuOrder' => 9, 'statusId' => 1, 'view' => 1, 'created' => 1, 'updated' => 1, 'cancelled' => 0, 'deleted' => 1, 'printed' => 0, 'downloaded' => 0, 'closed' => 0, 'verified' => 0, 'inputBy' => '', 'inputDate' => $now],
			['menuId' => 100015, 'menuPid' => 100009, 'menuTypeId' => 100001, 'menu' => 'PACKAGES', 'icon' => 'desc.png', 'url' => 'packages/manage', 'urlType' => '', 'menuLevel' => 3, 'title' => 'PACKAGES', 'menuOrder' => 11, 'statusId' => 1, 'view' => 1, 'created' => 1, 'updated' => 1, 'cancelled' => 0, 'deleted' => 1, 'printed' => 0, 'downloaded' => 0, 'closed' => 0, 'verified' => 0, 'inputBy' => '', 'inputDate' => $now],
			['menuId' => 100016, 'menuPid' => 100009, 'menuTypeId' => 100001, 'menu' => 'SHIPMENTS', 'icon' => 'desc.png', 'url' => 'shipments/manage', 'urlType' => '', 'menuLevel' => 3, 'title' => 'SHIPMENTS', 'menuOrder' => 12, 'statusId' => 1, 'view' => 1, 'created' => 1, 'updated' => 1, 'cancelled' => 0, 'deleted' => 1, 'printed' => 0, 'downloaded' => 0, 'closed' => 0, 'verified' => 0, 'inputBy' => '', 'inputDate' => $now],
			['menuId' => 100017, 'menuPid' => 100018, 'menuTypeId' => 100001, 'menu' => 'TRANSFER LOCATION', 'icon' => 'customer.png', 'url' => 'locationtransfers/manage', 'urlType' => '', 'menuLevel' => 3, 'title' => 'TRANSFER LOCATION', 'menuOrder' => 7, 'statusId' => 1, 'view' => 1, 'created' => 1, 'updated' => 1, 'cancelled' => 0, 'deleted' => 1, 'printed' => 0, 'downloaded' => 0, 'closed' => 0, 'verified' => 0, 'inputBy' => '', 'inputDate' => $now],
			['menuId' => 100018, 'menuPid' => 100001, 'menuTypeId' => 100001, 'menu' => 'INVENTORY', 'icon' => 'customer.png', 'url' => '-', 'urlType' => '', 'menuLevel' => 2, 'title' => 'INVENTORY', 'menuOrder' => 6, 'statusId' => 1, 'view' => 1, 'created' => 1, 'updated' => 0, 'cancelled' => 0, 'deleted' => 0, 'printed' => 0, 'downloaded' => 0, 'closed' => 0, 'verified' => 0, 'inputBy' => '', 'inputDate' => $now],
			['menuId' => 100019, 'menuPid' => 100009, 'menuTypeId' => 100001, 'menu' => 'DELIVERY ORDERS', 'icon' => 'desc.png', 'url' => 'deliveryOrders/manage', 'urlType' => '', 'menuLevel' => 3, 'title' => 'DELIVERY ORDERS', 'menuOrder' => 10, 'statusId' => 1, 'view' => 1, 'created' => 1, 'updated' => 1, 'cancelled' => 0, 'deleted' => 1, 'printed' => 0, 'downloaded' => 0, 'closed' => 0, 'verified' => 0, 'inputBy' => '', 'inputDate' => $now],
			['menuId' => 100020, 'menuPid' => 100011, 'menuTypeId' => 100001, 'menu' => 'REPRESENTATIVE', 'icon' => 'customer.png', 'url' => 'representatives/manage', 'urlType' => '', 'menuLevel' => 3, 'title' => 'REPRESENTATIVE', 'menuOrder' => 5, 'statusId' => 1, 'view' => 1, 'created' => 1, 'updated' => 1, 'cancelled' => 0, 'deleted' => 1, 'printed' => 0, 'downloaded' => 0, 'closed' => 0, 'verified' => 0, 'inputBy' => '', 'inputDate' => $now],
			['menuId' => 100023, 'menuPid' => 100001, 'menuTypeId' => 100001, 'menu' => 'PURCHASE', 'icon' => 'customer.png', 'url' => '/', 'urlType' => '', 'menuLevel' => 2, 'title' => 'PURCHASE', 'menuOrder' => 13, 'statusId' => 1, 'view' => 1, 'created' => 1, 'updated' => 1, 'cancelled' => 0, 'deleted' => 1, 'printed' => 0, 'downloaded' => 0, 'closed' => 0, 'verified' => 0, 'inputBy' => '', 'inputDate' => $now],
			['menuId' => 100024, 'menuPid' => 100023, 'menuTypeId' => 100001, 'menu' => 'PURCHASE ORDERS', 'icon' => 'customer.png', 'url' => 'purchaseorders/manage', 'urlType' => '', 'menuLevel' => 3, 'title' => 'PURCHASE ORDERS', 'menuOrder' => 14, 'statusId' => 1, 'view' => 1, 'created' => 1, 'updated' => 1, 'cancelled' => 0, 'deleted' => 1, 'printed' => 0, 'downloaded' => 0, 'closed' => 0, 'verified' => 0, 'inputBy' => '', 'inputDate' => $now],
			['menuId' => 100025, 'menuPid' => 100023, 'menuTypeId' => 100001, 'menu' => 'PURCHASE RECEIVES', 'icon' => 'customer.png', 'url' => 'purchasereceives/manage', 'urlType' => '', 'menuLevel' => 3, 'title' => 'PURCHASE RECEIVES', 'menuOrder' => 15, 'statusId' => 1, 'view' => 1, 'created' => 1, 'updated' => 1, 'cancelled' => 0, 'deleted' => 1, 'printed' => 0, 'downloaded' => 0, 'closed' => 0, 'verified' => 0, 'inputBy' => '', 'inputDate' => $now],
		];

		$this->db->query('SET FOREIGN_KEY_CHECKS=0');
		$this->db->query('TRUNCATE TABLE menu');
		$this->db->query('ALTER TABLE menu AUTO_INCREMENT = 100001');
		$this->db->table('menu')->insertBatch($data);
	}
}
