<?php

namespace App\Database\Seeds;

use CodeIgniter\Database\Seeder;

class ProductsSeeder extends Seeder
{
	public function run()
	{
		$now = date('Y-m-d H:i:s');

		$data = [
			['productId' => 100001, 'productNumber' => 'ACER-001', 'productName' => 'LAPTOP ACER T001', 'productType' => 4, 'priceCost' => 80.00, 'priceSell' => 100.00, 'length' => 0, 'width' => 0, 'height' => 0, 'weight' => 2000, 'unit' => 'Pcs', 'remark' => '', 'statusId' => 1, 'inputBy' => '100001', 'inputDate' => $now, 'updateBy' => '100001', 'updateDate' => $now, 'deleteBy' => '', 'deleteDate' => null],
			['productId' => 100002, 'productNumber' => 'HP-001', 'productName' => 'LAPTOP HP T001', 'productType' => 1, 'priceCost' => 90.00, 'priceSell' => 120.00, 'length' => 0, 'width' => 0, 'height' => 0, 'weight' => 2000, 'unit' => 'Pcs', 'remark' => '', 'statusId' => 1, 'inputBy' => '100001', 'inputDate' => $now, 'updateBy' => '100001', 'updateDate' => $now, 'deleteBy' => '', 'deleteDate' => null],
			['productId' => 100003, 'productNumber' => 'SLIM-3', 'productName' => 'Lenovo Slim 3', 'productType' => 5, 'priceCost' => 200.00, 'priceSell' => 500.00, 'length' => 100, 'width' => 50, 'height' => 2, 'weight' => 2000, 'unit' => 'Pcs', 'remark' => '', 'statusId' => 1, 'inputBy' => '100001', 'inputDate' => $now, 'updateBy' => '100001', 'updateDate' => $now, 'deleteBy' => '', 'deleteDate' => null],
			['productId' => 100004, 'productNumber' => 'MSI GAMING001', 'productName' => 'MSI 001', 'productType' => 2, 'priceCost' => 100.00, 'priceSell' => 100.00, 'length' => 100, 'width' => 0, 'height' => 0, 'weight' => 9999, 'unit' => 'Pcs', 'remark' => '', 'statusId' => 1, 'inputBy' => '100001', 'inputDate' => $now, 'updateBy' => '100001', 'updateDate' => $now, 'deleteBy' => '', 'deleteDate' => null],
			['productId' => 100005, 'productNumber' => 'TEST', 'productName' => '123', 'productType' => 1, 'priceCost' => 0.00, 'priceSell' => 0.00, 'length' => 0, 'width' => 0, 'height' => 0, 'weight' => 20, 'unit' => 'Pcs', 'remark' => '', 'statusId' => 0, 'inputBy' => '100001', 'inputDate' => $now, 'updateBy' => '', 'updateDate' => $now, 'deleteBy' => '100001', 'deleteDate' => $now],
			['productId' => 100006, 'productNumber' => 'TEST GAMING', 'productName' => 'GAMING', 'productType' => 1, 'priceCost' => 100.00, 'priceSell' => 200.00, 'length' => 0, 'width' => 0, 'height' => 0, 'weight' => 2000, 'unit' => 'Pcs', 'remark' => '', 'statusId' => 1, 'inputBy' => '100001', 'inputDate' => $now, 'updateBy' => '100001', 'updateDate' => $now, 'deleteBy' => '', 'deleteDate' => null],
			['productId' => 100007, 'productNumber' => 'BS4', 'productName' => 'BLACK SHARK 4', 'productType' => 3, 'priceCost' => 4500000.00, 'priceSell' => 8000000.00, 'length' => 0, 'width' => 0, 'height' => 0, 'weight' => 900, 'unit' => 'Box', 'remark' => '', 'statusId' => 2, 'inputBy' => '100001', 'inputDate' => $now, 'updateBy' => '100001', 'updateDate' => $now, 'deleteBy' => '100001', 'deleteDate' => $now],
			['productId' => 100008, 'productNumber' => 'ROG5', 'productName' => 'ROG PHONE 5', 'productType' => 3, 'priceCost' => 1200000.00, 'priceSell' => 1500000.00, 'length' => 0, 'width' => 0, 'height' => 0, 'weight' => 900, 'unit' => 'Pcs', 'remark' => '', 'statusId' => 1, 'inputBy' => '100001', 'inputDate' => $now, 'updateBy' => '', 'updateDate' => $now, 'deleteBy' => '', 'deleteDate' => null],
			['productId' => 100009, 'productNumber' => '123123', 'productName' => 'Keyboard Xiaomi M3', 'productType' => 1, 'priceCost' => 10000.00, 'priceSell' => 11000.00, 'length' => 0, 'width' => 0, 'height' => 0, 'weight' => 500, 'unit' => 'Pcs', 'remark' => '', 'statusId' => 1, 'inputBy' => '100001', 'inputDate' => $now, 'updateBy' => '100001', 'updateDate' => $now, 'deleteBy' => '', 'deleteDate' => null],
			['productId' => 100010, 'productNumber' => 'HOLDER001', 'productName' => 'HOLDER SENSOR COVER PRINTER', 'productType' => 3, 'priceCost' => 800.00, 'priceSell' => 1200.00, 'length' => 0, 'width' => 0, 'height' => 0, 'weight' => 100, 'unit' => 'Pcs', 'remark' => '', 'statusId' => 1, 'inputBy' => '100001', 'inputDate' => $now, 'updateBy' => '', 'updateDate' => $now, 'deleteBy' => '', 'deleteDate' => null],
			['productId' => 100011, 'productNumber' => 'HOLDER002', 'productName' => 'HOLDER SIELD PLATE', 'productType' => 3, 'priceCost' => 800.00, 'priceSell' => 1200.00, 'length' => 0, 'width' => 0, 'height' => 0, 'weight' => 100, 'unit' => 'Pcs', 'remark' => '', 'statusId' => 1, 'inputBy' => '100001', 'inputDate' => $now, 'updateBy' => '', 'updateDate' => $now, 'deleteBy' => '', 'deleteDate' => null],
			['productId' => 100012, 'productNumber' => 'HOLDER003', 'productName' => 'HOLDER PULLEY', 'productType' => 3, 'priceCost' => 800.00, 'priceSell' => 1200.00, 'length' => 0, 'width' => 0, 'height' => 0, 'weight' => 100, 'unit' => 'Pcs', 'remark' => '', 'statusId' => 1, 'inputBy' => '100001', 'inputDate' => $now, 'updateBy' => '', 'updateDate' => $now, 'deleteBy' => '', 'deleteDate' => null],
			['productId' => 100013, 'productNumber' => 'HOUSING001', 'productName' => 'HOUSING RIGHT RUFUS', 'productType' => 3, 'priceCost' => 800.00, 'priceSell' => 1200.00, 'length' => 0, 'width' => 0, 'height' => 0, 'weight' => 100, 'unit' => 'Pcs', 'remark' => '', 'statusId' => 1, 'inputBy' => '100001', 'inputDate' => $now, 'updateBy' => '', 'updateDate' => $now, 'deleteBy' => '', 'deleteDate' => null],
			['productId' => 100014, 'productNumber' => 'HOPPER002', 'productName' => 'HOPPER #2', 'productType' => 3, 'priceCost' => 800.00, 'priceSell' => 1200.00, 'length' => 0, 'width' => 0, 'height' => 0, 'weight' => 100, 'unit' => 'Pcs', 'remark' => '', 'statusId' => 1, 'inputBy' => '100001', 'inputDate' => $now, 'updateBy' => '', 'updateDate' => $now, 'deleteBy' => '', 'deleteDate' => null],
			['productId' => 100015, 'productNumber' => 'HOUSING002', 'productName' => 'HOUSING RIGHT ROBBEN', 'productType' => 3, 'priceCost' => 800.00, 'priceSell' => 1200.00, 'length' => 0, 'width' => 0, 'height' => 0, 'weight' => 100, 'unit' => 'Pcs', 'remark' => '', 'statusId' => 1, 'inputBy' => '100001', 'inputDate' => $now, 'updateBy' => '', 'updateDate' => $now, 'deleteBy' => '', 'deleteDate' => null],
			['productId' => 100016, 'productNumber' => 'EDGE001', 'productName' => 'EDGE GUIDE REAR RIGHT B', 'productType' => 3, 'priceCost' => 800.00, 'priceSell' => 1200.00, 'length' => 0, 'width' => 0, 'height' => 0, 'weight' => 100, 'unit' => 'Pcs', 'remark' => '', 'statusId' => 1, 'inputBy' => '100001', 'inputDate' => $now, 'updateBy' => '', 'updateDate' => $now, 'deleteBy' => '', 'deleteDate' => null],
			['productId' => 100017, 'productNumber' => 'EDGE002', 'productName' => 'EDGE GUIDE REAR LEFT B', 'productType' => 3, 'priceCost' => 800.00, 'priceSell' => 1200.00, 'length' => 0, 'width' => 0, 'height' => 0, 'weight' => 100, 'unit' => 'Pcs', 'remark' => '', 'statusId' => 1, 'inputBy' => '100001', 'inputDate' => $now, 'updateBy' => '', 'updateDate' => $now, 'deleteBy' => '', 'deleteDate' => null],
			['productId' => 100018, 'productNumber' => 'ROLLER001', 'productName' => 'ROLLER PAPER EJECT DRIVEN', 'productType' => 3, 'priceCost' => 800.00, 'priceSell' => 1200.00, 'length' => 0, 'width' => 0, 'height' => 0, 'weight' => 100, 'unit' => 'Pcs', 'remark' => '', 'statusId' => 1, 'inputBy' => '100001', 'inputDate' => $now, 'updateBy' => '', 'updateDate' => $now, 'deleteBy' => '', 'deleteDate' => null],
			['productId' => 100019, 'productNumber' => 'COVER001', 'productName' => 'COVER CASSETE', 'productType' => 3, 'priceCost' => 800.00, 'priceSell' => 1200.00, 'length' => 0, 'width' => 0, 'height' => 0, 'weight' => 100, 'unit' => 'Pcs', 'remark' => '', 'statusId' => 1, 'inputBy' => '100001', 'inputDate' => $now, 'updateBy' => '', 'updateDate' => $now, 'deleteBy' => '', 'deleteDate' => null],
			['productId' => 100020, 'productNumber' => 'SHEET001', 'productName' => 'SHEET GUIDE B', 'productType' => 3, 'priceCost' => 800.00, 'priceSell' => 1200.00, 'length' => 0, 'width' => 0, 'height' => 0, 'weight' => 100, 'unit' => 'Pcs', 'remark' => '', 'statusId' => 1, 'inputBy' => '100001', 'inputDate' => $now, 'updateBy' => '', 'updateDate' => $now, 'deleteBy' => '', 'deleteDate' => null],
		];

		$this->db->query('TRUNCATE TABLE products');
		$this->db->query('ALTER TABLE products AUTO_INCREMENT = 100001');
		$this->db->table('products')->insertBatch($data);
	}
}
